# Generated by Django 4.2.1 on 2023-05-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_fersion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prouser',
            name='money',
            field=models.CharField(default=200, max_length=230),
        ),
    ]
