# Generated by Django 4.2.1 on 2023-07-09 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_exercises_namecategory_remove_students_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeExercises',
            fields=[
                ('exercises_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='category.exercises')),
            ],
            bases=('category.exercises',),
        ),
        migrations.CreateModel(
            name='HandExercises',
            fields=[
                ('exercises_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='category.exercises')),
            ],
            bases=('category.exercises',),
        ),
        migrations.CreateModel(
            name='NeckExercises',
            fields=[
                ('exercises_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='category.exercises')),
            ],
            bases=('category.exercises',),
        ),
    ]
