# Generated by Django 4.2.1 on 2023-05-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_rotations', models.CharField(max_length=230)),
                ('pull_ups', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercises_number_one', models.CharField(max_length=230)),
                ('exercises_number_two', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='LegExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warm_up', models.CharField(max_length=230)),
                ('jumping', models.CharField(max_length=230)),
                ('sit_ups', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='EyeExercises',
            fields=[
                ('exercises_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fitnes.exercises')),
            ],
            bases=('fitnes.exercises',),
        ),
        migrations.CreateModel(
            name='HandExercises',
            fields=[
                ('exercises_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fitnes.exercises')),
            ],
            bases=('fitnes.exercises',),
        ),
        migrations.CreateModel(
            name='NeckExercises',
            fields=[
                ('exercises_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fitnes.exercises')),
            ],
            bases=('fitnes.exercises',),
        ),
    ]
