# Generated by Django 4.2.1 on 2023-05-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnes', '0002_alter_exercises_exercises_number_one_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackExercises',
        ),
        migrations.DeleteModel(
            name='LegExercises',
        ),
    ]
